export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const DELETE_USER = "DELETE_USER";
export const FETCH_DELETE_USER_SUCCESS = "FETCH_DELETE_USER_SUCCESS";